#mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml

#datasource
spring:
  datasource:
    url: jdbc:mysql://192.168.110.128:3306/hr?useUnicode=true&characterEncoding=utf-8
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

#添加secret和expire
JWT:
  secret: qwertyuiopasdfghjklzxcvbnmbdhgfgtgdfgfdg
  expire: 6000000
server:
  port: 8888
